# Generated by Django 5.0.2 on 2024-03-06 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.CharField(max_length=150, unique=True)),
                ('phone_number', models.CharField(max_length=150)),
                ('company_name', models.CharField(max_length=150)),
                ('company_notes', models.TextField()),
                ('arrived_date', models.DateField()),
            ],
            options={
                'db_table': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_title', models.CharField(max_length=100)),
                ('deal_status', models.CharField(choices=[('O', 'Open'), ('W', 'Won'), ('L', 'Lost')], max_length=30)),
                ('expected_close_date', models.DateField()),
                ('deal_amount', models.IntegerField()),
                ('deal_withCustomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRMApp.customer')),
            ],
            options={
                'db_table': 'Deal',
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interacted_mode', models.CharField(choices=[('E', 'Email'), ('C', 'Call'), ('M', 'Meeting')], max_length=30)),
                ('interacted_time', models.DateTimeField()),
                ('interaction_notes', models.TextField()),
                ('interacted_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRMApp.customer')),
            ],
            options={
                'db_table': 'Interaction',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=100)),
                ('task_status', models.CharField(choices=[('O', 'Open'), ('D', 'Done')], max_length=30)),
                ('task_description', models.TextField()),
                ('task_duedate', models.DateField()),
                ('task_relatedtodeal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRMApp.deal')),
            ],
            options={
                'db_table': 'Task',
            },
        ),
    ]
